In [11]:
import torch

In [12]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 32, -48, -29,  10,  29,  17])

In [13]:
tensor = torch.tensor([[0.1, 1.2],[2.2, 3.1],[4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [14]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
input1 = torch.empty(2, 3)
input1

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [23]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [24]:
linspace = torch.linspace(3,10,steps=6)
linspace

tensor([ 3.0000,  4.4000,  5.8000,  7.2000,  8.6000, 10.0000])

In [26]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [27]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [30]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])